name: github_discover
description: GitHub Discover - Desenvolvimento Cross Platform - FIAP.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  dio: ^5.3.2
  envied: ^0.3.0+3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  get_it: ^7.6.4
  go_router: ^10.1.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  flutter_lints: ^2.0.2
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/logos/

  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Display-Black.otf
          weight: 900
